gems:
  - jekyll-seo-tag
title: International Workshop on SRMPDS
description: Homepage of the AI-Science Workshop. 
url: https://ai-science.github.io/
social:
  name: AI-Science Workshop
show_downloads: false
google_analytics:
theme: 
